### PR TITLE
Add getter for callback in KeybindMulti

### PR DESCRIPTION
**Pull request by HughBone**
This would allow you to activate key actions via other means ( ͡° ͜ʖ ͡°)

(Currently working on a mod in which this functionality would be useful)

### CODE REVIEW

**Comment by maruohon** [comment]
I can add this for now if you need it... but it would be a temporary solution and completely obsolete already in the current main development code in the liteloader branch.

In that main dev code I have already separated all the stuff that runs from hotkeys into a generic "action system", and the hotkeys in most cases are just created wrapper callback that call one of those actions. There are also some "parameterized actions" and you can create an alias for those, where you pre-bind the parameter. You can also create macros, which are basically just lists of actions. (The macros can also be used as a "pre-filtered" list in the action prompt instead of being executed as a macro.)

The actions can also be run via an "action prompt" and also in the past few days I've been implementing an "action widget screen" where you can add custom buttons that run an action. You can also bind custom hotkeys to actions.

**Comment by HughBone** [comment]
I'm working on something similar to your action widget screen (although mine pales in comparison haha). I'm guessing you plan to update liteloader to 1.16/1.17? Either way, you can go ahead and add this, I don't mind updating my code in the future.

**Comment by maruohon** [comment]
All my client mods are still mainly developed on 1.12.2 for LiteLoader, and the code is then occasionally ported from that to the 1.13.2+ versions. (The last port happened all the way back in June 2019 though... :pain:)

Still no idea how long it will be until everything is ready for the next merge from 1.12.2 to 1.13.2+, so I'll merge this for now so you can use it until all the new updates are ready at some point.

**Comment by maruohon** [comment]
Okay that new build is now on my maven, and also for players on my server: https://masa.dy.fi/mcmods/client_mods/?mcver=1.16.4

Do you also need it on CurseForge for other players, or is the above link enough for now?

**Comment by HughBone** [comment]
That link is good for now, thanks.

**Pull request merged**
