### PR TITLE
Update to 1.21.3 (not fully tested)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by sakura-ryoko** [comment]
1.21.3 has already been completed & tested.  See https://github.com/sakura-ryoko/malilib

**Comment by ghost** [comment]
Why is there no pr if it is already complete?

**Comment by sakura-ryoko** [comment]
> Why is there no pr if it is already complete?

Because Masa has been using and uploading from my Repo since 1.20.6.  He will only clone my repo if he builds it himself for Modrinth, etc.  If you take a look, you will see that I have upload access to Modrinth, and will do so whenever the mods are deemed more stable.  You can always offer PR's under my Repos if you would like to help out.  PR's are welcome; especially for bug hunting and whatnot.

Help is always appreciated; but just trying not to have you stress out over this port more than you need to.

**Comment by ghost** [comment]
All development is happening on your repo and this one just exists now?

**Comment by sakura-ryoko** [comment]
> All development is happening on your repo and this one just exists now?

Correct, as I often track the snaps as they get released under a sub-branch.  Feel free to offer support there. :)

**Pull request closed without merging**
