### PR TITLE
1.20.6-DEV Merge

### PR DESCRIPTION
**Pull request by sakura-ryoko**
I accidentally merged my DEV branch making the original one too ugly...
Draft RC.2 Clean Merge from DEV branch.
- Includes a direct clone of SRC folder.
- Gradle 8.7 files.
- Lacks: build.gradle / gradle.properties
- Requires: Java 21 / Fabric-Loom 1.6 / fabric-network-api
- Modmenu (A newer build after alpha.3 that doesn't break malilib at launch)

Fixes / Changes:

- Fixes MOD_VERSION to be displayed in the config menu.
- Allows the mod to actually save the "Debug" section of the settings to the config file.\
- Introduces the ServerHandler interfaces, for Server-related events (More on this later)
- Converts the majority of the Rendering code to be Matrix4f / Matrix4fStack compliant, with a few exceptions, such as DrawContext.
- Fixes WorldLoadHandler's "joinWorld / disconnect" code to work with the new version.
- Removes legacy PluginChannelHandler and PacketSplitter code in favor of a totally new Network API that supports the new CustomPayload format, and Fabric Networking API 4.0.0+. There is a lot to explain on this subject in addition to the new Client and Server side Packet / Channel Handler interfaces.
- Fixed several functions under InventoryUtils to work with the new Data Components interface under Minecraft, such as replacing the getStoredItems() for shulker boxes.
- Added functions for getBundleItems() to match it's Shulker box counterpart.
- Moved the "getItemStackFromString()" function to MaLiLib from Litematica, and expanded it to allow both Item counts, and Data Components as parameters. This function is used across various mods.
- Added "getHighestSectionYOffset()" function to WorldUtils to replace the Vanilla "getHighestNonEmptySectionYOffset()" which is marked for removal.

### CODE REVIEW

**Comment by sakura-ryoko** [comment]
I'm going to further expand on the IPluginClientPlayHandler<> interface.

**Comment by watertrainer** [comment]
I was able to compile everything with the provided build.gradle, minihud, litematica and tweakeroo worked like a charm ingame as well

**Comment by sakura-ryoko** [comment]
> I was able to compile everything with the provided build.gradle, minihud, litematica and tweakeroo worked like a charm ingame as well

Did you change them to 1.20.5, though ?  Also there are .JAR files in the repos.

**Comment by watertrainer** [comment]
> > I was able to compile everything with the provided build.gradle, minihud, litematica and tweakeroo worked like a charm ingame as well
> 
> Did you change them to 1.20.5, though ? Also there are .JAR files in the repos.  

I didn't have to change anything in the gradle files, they were set to 1.20.5 already and the compiled files worked for me (with your branches of those mods as well). I had to add a new libs folder in tweakeroo, minihud and litematica and add the custom malilib, but apart from that all the preset settings etc. worked for me

**Comment by sakura-ryoko** [comment]
> I didn't have to change anything in the gradle files, they were set to 1.20.5 already and the compiled files worked for me (with your branches of those mods as well). I had to add a new libs folder in tweakeroo, minihud and litematica and add the custom malilib, but apart from that all the preset settings etc. worked for me

You must have used the -DEV branch then.  This PR is a src file clone of the DEV branch, minus the build scripts.
And correct, you just need to copy the malilib to the libs folder --> or just download the existing JAR files.

**Pull request closed without merging**
